version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80" 
    volumes:
      - .:/var/www/html 
    depends_on:
      - db  
    networks:
      - laravel_network

  db:
    image: mysql:5.7
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: indeed_admin
      MYSQL_USER: indeed_user
      MYSQL_PASSWORD: test_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
volumes:
  db_data:
